public/docs/ts/latest/guide/attribute-directives.jade

刚看到这句话“directives 数组”，一下没懂，点看英文才知道原来说的是`@Component`的。
BTW, 非常感谢翻译成中文！

add lost @Component back

---

public/_includes/_main-nav.jade

This avoid that ugly flash when the page loads.

chore: hide the english toggle link until angular is loaded

---

public/docs/ts/latest/quickstart.jade

在 angular2-quickstart 中,根据上下文,这里应当创建一个 ` styles.css`  文件, 原文漏写一个 `s` 
ps: 感谢你们的翻译工作

rename style.css to styles.css ,add "s"

---

public/docs/ts/latest/cookbook/aot-compiler.jade

修正一个笔误：重新编译

---

public/docs/ts/latest/guide/router.jade

fix: guide/router some error

---

public/docs/ts/latest/guide/npm-packages.jade

Fixed `Polyfile` to `Polyfill`

Fixed typo

---

public/docs/ts/latest/tutorial/index.jade

由于读者看到的图片仍为英文，翻译中使用“Dashboard（控制台）“形式，方便读者对照。

Polish toh index 

---

public/docs/ts/latest/guide/ngmodule.jade
public/docs/ts/latest/index.jade
public/resources/css/_translate.scss
public/translate/cn/translate.js

Fixes translate.js

---

public/docs/ts/latest/guide/dependency-injection.jade
public/docs/ts/latest/guide/style-guide.jade
public/docs/ts/latest/quickstart.jade
public/translate/cn/translate.js

1. cheatsheet不正常
2. 自动在英文单词左右加空格的函数还需要改进

Translate js refactor

---

public/docs/ts/latest/guide/dependency-injection.jade
public/resources/css/_translate.scss

Polish dependency-injection.jade

---

public/docs/ts/latest/guide/_data.json
public/docs/ts/latest/guide/style-guide.jade
public/translate/cn/translate.js

1、translate.js忽略`strong`标签。
2、更新guide/_data.json中的翻译（空格）。

Polish style-guild.jade

---

public/docs/ts/latest/guide/learning-angular.jade

Polish learning-angular.jade (round 2)

---

public/docs/ts/latest/guide/setup.jade

Polish setup.jade (round 2)

---

public/docs/ts/latest/guide/index.jade

Polish guild/index.jade (round 2)

---

public/docs/ts/latest/guide/architecture.jade

Polish architecture.jade (round 2)

---

public/docs/ts/latest/guide/displaying-data.jade

Polish displaying-data.jade (round 2)

---

public/docs/ts/latest/guide/user-input.jade

Polish user-input.jade (round 2)

---

public/docs/_data.json
public/docs/ts/latest/_data.json
public/docs/ts/latest/cookbook/_data.json
public/docs/ts/latest/guide/_data.json
public/docs/ts/latest/tutorial/_data.json

Fix all _data.json

---

public/docs/ts/latest/tutorial/index.jade

Polish tutorial/index.jade (round 2)

---

public/docs/ts/latest/tutorial/toh-pt2.jade

Polish toh-pt2.jade (round 2)

---

public/docs/ts/latest/index.jade

Polish latest/index.jade

---

public/docs/ts/latest/tutorial/toh-pt6.jade

Polish toh-pt6.jade (round 2)

---

public/docs/ts/latest/guide/template-syntax.jade

Fixes issue 127

---

public/docs/ts/latest/guide/setup.jade

Fixes issue 181

---

public/docs/ts/latest/tutorial/toh-pt6.jade

Fix tutorial-http toh-pt6.jade

Fix tutorial - http

---

public/docs/ts/latest/guide/webpack.jade
public/docs/ts/latest/tutorial/toh-pt6.jade

duplicate ### HeroSearchComponent

Update toh-pt6.jade duplicate ### HeroSearchComponent

---

aio/content/tutorial/index.md

docs(tutorial): fix demo broken link

---

aio/content/guide/router.md

spelling mistake

---

aio/content/guide/testing.md

fix(doc:testing): replace faceAsync with fakeAsync

---

aio/content/guide/architecture.md

remove the wrong duplicate code to fix break style in page.

fix break style in architecture doc

---

aio/content/guide/architecture.md
aio/content/guide/dependency-injection-in-action.md
aio/content/guide/forms.md
aio/content/guide/router.md
aio/content/guide/template-syntax.md
aio/content/tutorial/toh-pt1.md
aio/content/tutorial/toh-pt4.md
aio/content/tutorial/toh-pt5.md

1.它/她 => 他/她 or other better expression.
2.some of 英雄.+它们 => 英雄.+他们
3.some of 它们.+他们 => 他们.+英雄
注意：

Fixed some typos

---

aio/content/guide/testing.md
aio/content/tutorial/toh-pt3.md
aio/content/tutorial/toh-pt4.md

Update some translation errors and typo

fixed some translation errors and typo

---

aio/content/guide/architecture.md

Fix typo in architecture.md

---

aio/content/guide/architecture-modules.md

architecture-modules.md: 修改错别字

---

aio/content/guide/architecture-services.md
aio/content/guide/dynamic-form.md
aio/content/guide/form-validation.md
aio/content/guide/forms.md
aio/content/guide/router.md
aio/content/guide/testing.md
aio/content/guide/user-input.md
aio/content/tutorial/toh-pt4.md

请教一下,在本次PR时发现之前已经PR过的内容也被检测为差异.
这个对你们merge有影响吗?我需要每次PR之后都删除这个远程分支吗?

 fix:错别字及语法 

---

aio/content/guide/aot-compiler.md

fix(aot-compiler.md): 修正错别字

---

aio/content/guide/ngmodule-faq.md
aio/content/navigation.json

Update: navigation.json

---

aio/content/guide/testing.md

docs: fix 'marbles' translation

---

aio/content/guide/router.md

fix:修复路由和导航章节中的一个表述错误

---

aio/content/guide/router.md

fix:修正路由与导航章节的一个翻译错误

---

aio/content/tutorial/toh-pt4.md

docs: 修改一个翻译错误

---

aio/content/guide/architecture-components.md

fix broken link

---

aio/content/guide/feature-modules.md

注意：
commit 说明：
对《特性模块》章节中一处翻译错误进行更正

fix: correct a translation error in the 'Feature Modules' section

---

aio/content/guide/architecture-components.md

docs: Holds an array不是从服务中取到

---

aio/content/guide/lifecycle-hooks.md

docs: 因为只调用一次，应该是当

---

aio/content/guide/module-types.md

翻译问题：导出改成导入

---

aio/content/guide/lifecycle-hooks.md

docs: 修改错字

---

aio/content/guide/dependency-injection-providers.md

docs: fix typo

---

aio/content/guide/complex-animation-sequences.md

fixed translate

---

aio/content/guide/entry-components.md

docs: 将“也不没有在模板中使用过”改为“也没有在模板中使用过”

---

aio/content/guide/singleton-services.md

docs: 将“这算模式”改为“这种模式”

---

aio/content/guide/forms-overview.md

docs: 翻译错误修正

---

aio/content/guide/router.md

原文与翻译内容不一致，admin-routing.module.ts 写成了 crisis-center.routes.ts

fix: 修改翻译错误

---

aio/content/guide/structural-directives.md

docs: 显示错误修正

---

aio/content/guide/structural-directives.md

docs:  翻译错误修正

---

aio/content/guide/module-types.md

docs: 翻译修正

---

aio/content/guide/router.md

fixed router page duplicate words.

---

packages/core/src/metadata/directives.ts

fixed directive outputs with the correct sample

---

aio/content/guide/upgrade.md

修改upgradeAdapter.downgradeNg2Provider 为原文使用的 downgradeInjectable
注意：

使用 downgradeInjectable

---

aio/content/start/index.md

Semantic correction

---

aio/content/guide/frequent-ngmodules.md

docs: 修改有歧义的文字

---

aio/content/guide/testing.md

模拟板 -> 模拟版

---

aio/content/guide/security.md

补全缺失的URL。
Fix the missing URL.

补全缺失的链接URL

---

aio/content/guide/architecture-components.md

fix(architecture-modules): 指令类型举例中的翻译错误

---

aio/content/guide/architecture.md

笔误：商逻辑 => 程序逻辑

---

aio/content/guide/http.md

docs: 翻译改进

---

aio/content/guide/aot-compiler.md

Issue https://github.com/angular/angular-cli/issues/17736#issuecomment-629995982

fix: 更新「选择编译器」一节以同步官方最新文档

---

aio/content/guide/elements.md

docs: 文案错误

---

aio/content/guide/pipes.md

docs: 文字错误

---

aio/content/guide/template-syntax.md

docs: 修改语义错误，防止xx不要xx

---

aio/content/guide/displaying-data.md

docs: 重复内容

---

aio/tools/transforms/angular.io-package/processors/processNavigationMap.js

为 "快速上手->管理数据" 一节添加翻译 Add translation for "managing-data" section.

---

packages/core/src/metadata/directives.ts

ViewEncapsulation.None -> ViewEncapsulation.ShadowDom
注意：

docs(core): 翻译错误

---

aio/content/guide/universal.md

docs: 错别字（typo）

---

aio/content/guide/deployment.md

docs: Remove duplicated words.
