- public/docs/ts/latest/guide/dependency-injection.jade
因为英文原文中那个私有变量是`logger`所以我觉得还是用`logger`比较好。
> 翻译的一点修改: _logger修改为logger

- public/docs/ts/latest/glossary.jade
每个 Angular 应用程序都有一个应用程序根模块类。按规约这个类的名字为 AppModule ，存放在名为 app.component.ts 的文件。
->
每个 Angular 应用程序都有一个应用程序根模块类。按规约这个类的名字为 AppModule ，存放在名为 app.module.ts 的文件。
> AppModule 在 app.module.ts内 原文也错了

- public/docs/ts/latest/tutorial/toh-pt6.jade
原文：we can chain `Observable` operators to the string `Observable`
译文应该是串联一些操作符而不是一个操作符
> 修正 教程 7.Http 翻译问题

- public/docs/ts/latest/guide/testing.jade
修改主要有2点原因：
1. 阅读到此的时候如果不注意到 *如下* 是一个链接的话，很可能下意识的认为接下来的一段是用来说明的原因，但其实又和原因不相关，造成读者困惑。
2. 改为 原因在这里有所解释 是和下面的测试组件小节中的 ”对应的 app/banner-component.spec.ts 处于与组件相同的目录，原因在 这里 有所解释。“  保持翻译一致。
> (测试一章):文字优化 消除歧义

- public/translate/cn/translate.js
英文中包含[`&#8203;`](http://www.fileformat.info/info/unicode/char/200b/index.htm)。
Fix #122.
> fix issue 122

- public/resources/css/_translate.scss
- public/translate/cn/translate.js
1. 访问节点的`textContent`，而不是`innerText`。访问`innerText`会引起reflow，降低性能。
2. 只访问`.docs-content`下的节点，减少节点访问数量。
3. 采用递归方式访问节点，提高效率，避免反复访问节点。
4. 调整英文的`margin-top`，增加中英文对照的视觉相关性。
5. 调整`<li>`中`<p>`的margin，与普通`<li>`的外观保持一致。
6. 处理前先隐藏`.docs-content`，处理完成后显示，避免中文版开始时出现英文。Fixes #76
> Refactoring translate.js

- aio/content/translations/cn/home.md
Angular documentation no longer have non-TypeScript editions.
> docs(aio): remove outdated statement

- aio/content/examples/form-validation/src/app/shared/forbidden-name.directive.ts
修改`selector: '[forbiddenName]',`指令选择器值与组件模板中的指令不一致的错误。
> 修改指令选择器的值错误

- public/docs/ts/latest/guide/hierarchical-dependency-injection.jade
https://angular.cn/guide/dependency-injection-in-action
'tree' is not 'three', so ‘这三个注入器’ should be ‘输入器树’
> 修改依赖注入章节的某处翻译错误

- aio/content/guide/router.md
> 通过在 `AppModule` 中导入 `AppRoutingModule` 并再次导出 `RouterModule`，那些声明在 `AppModule` 中的组件就可以访问路由指令了，比如 `RouterLink` 和 `RouterOutlet`。
这句翻译很容易造成一些理解上的困难和错误，因为`AppModule`并不需要也不会再次导出`RouterModule`，事实上，`AppModule`不会导出任何模块。
我想它本来想表达的意思是
>  通过在`AppRoutingModule` 再次导出 `RouterModule`，然后在 `AppModule` 中导入 `AppRoutingModule`，那些声明在 `AppModule` 中的组件就可以访问路由指令了，比如 `RouterLink` 和 `RouterOutlet`。
所以我做了一些修改，避免原来的语句表述造成的歧义。
注意：
> fix: 修正翻译的一个语义错误

- aio/content/guide/router.md
修复路由与导航章节里程碑部分的一个标题的序号和格式问题，保证标题观感上的一致。
注意：
> fix:修复路由与导航章节的目录序号及格式

- aio/content/guide/quickstart.md
`launches the server` ?  `启动服务器` : `开发服务器`
> docs: fix typo

- packages/forms/src/validators.ts
原译文：
验证器就是一个函数，它可以处理单个 `FormControl` 好一组控件，
修改后：
验证器就是一个函数，它可以处理单个 `FormControl` 或一组控件，
注意：
> docs(forms): 修复错别字

- aio/content/guide/schematics-for-libraries.md
> docs: line 277:“schema.ts”改为“schema.json”

- aio/content/guide/schematics-for-libraries.md
根据上下文，此处properties指的是schema.json的properties属性，故不需要翻译成中文。跟上文的id,title,type一样，不需要翻译
注意：
> docs: line 260,“属性”改为“properties”

- aio/content/guide/component-styles.md
把伪类 `::ng-deep` 应用到如何一条 CSS 规则上就会完全禁止对那条规则的视图包装。
应翻译为
把伪类 `::ng-deep` 应用到任何一条 CSS 规则上就会完全禁止对那条规则的视图包装。
注意：
> docs:  翻译错误修正

- aio/content/guide/structural-directives.md
> docs: 翻译错误修正

- aio/content/guide/rx-library.md
生搬硬套的英文翻译并不是很好，我觉得再英文原有的意思之上使用更加中文化的翻译会更好一些
注意：
> docs: 文档翻译改进

- aio/content/guide/updating-to-version-9.md
> docs: 文档关于9.0 ts版本描述错误

- aio/content/start/routing.md
原文：`Define the product property and inject the ActivatedRoute into the constructor by adding it as an argument within the constructor's parentheses.`
如果翻译为：”定义 product 属性，并把它加入构造函数括号中作为参数，以便把 ActivatedRoute 注入到构造函数中。“，则语意上是把 product 属性加入构造函数。实际不是，实际是把 `route` 加入构造函数中。
原文中的 `it` 不是指代 `product`，而是指代路由对象。
注意：
> "it" 并非指 "product" 属性

- aio/content/guide/hierarchical-dependency-injection.md
#479 ，好像删除空行并没有两个行进入同一序列。之前的 #480 没有起到效果。我删掉了同一序列中两个空行的一行。顺便手工将序号修正。
注意：
> docs: 翻译修正

- aio/content/guide/component-overview.md
> 要在单独的文件中声明组件的样式，就要把 `stylesUrls` 属性添加到 `@Component` 装饰器中。
`stylesUrls` 应该为 `styleUrls`
注意：
> docs: Angular Component 概述 —— 声明组件的样式 段落中单词错误
